
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BAVC Resources
description: This site documents the policies and procedures of BAVC Media, a non-profit media digitization lab located in Oakland, CA
search_enabled: true
remote_theme: pmarsceill/just-the-docs
search_enabled: true
search.previews: 3
search_tokenizer_separator: /[\s/]+/
#heading_anchors: true
color_scheme: "dark"
baseurl: "/bavc-resources" # the subpath of your site, e.g. /blog
#theme: "just-the-docs"
aux_links:
  "BAVC Resources source on GitHub":
    - "//github.com/bavc/bavc-resources"
